### ISSUE TITLE
Setup Bootstrap Sass design system testing environment

### ISSUE THREAD

**Issue by guylepage3** [galaxypi/galaxy.ooo#13]
## Setup Bootstrap Sass design system testing environment
Upon designing out the layout, grid and colors, it became apparent, that in order to accurately define global values, we would need to set up a testing environment so that we can see how a variable will effect all components.

----

#### [Run the Bootstrap Docs App](http://getbootstrap.com/docs/4.1/getting-started/build-tools/#local-documentation)
- From the root `/bootstrap` directory, run `npm run docs-serve` in the command line.
- Open [`http://localhost:9001`](http://localhost:9001) in your browser.

----

### Tasks
- [x] [Research what will work best](#research-best-environment)
    - [x] ~~Custom Sass setup~~
    - [x] Bootstrap Docs setup **‹ -- (CHOSEN METHOD!)**
- [x] Download and install Bootstrap docs environment
- [x] Install and setup all build tools - http://getbootstrap.com/docs/4.1/getting-started/build-tools/
    - [x] Setup Java to run on Mac
- [x] Write documentation on setup for contributors

#### 1. Custom Sass setup
This method was not the best setup as it does not include very many classes and/or components. It also does not include automated build & compiling tools.

Build a custom bootstrap test environment using Sass as build tool.
- Created directory
- `npm init`
- Installed the latest version of Bootstrap 4 - `npm install bootstrap`
- `npm install`
- Copied html from one of the Bootstrap examples http://localhost:9001/docs/4.1/examples/
- Installed Sass `npm install -g sass` https://sass-lang.com/install
- Created a `primary.scss`
- Created a `primary.css`
- Created an `index.html` 
- Copied & pasted the html from http://getbootstrap.com/docs/4.1/examples/navbar-static/ into `index.html`
- To run the site and test modified Bootstrap Sass
    - Load the `index.html` file in the browser
    - Run `sass primary.scss primary.css`
    - Refresh browser to see changes

#### 2. Bootstrap Docs setup **‹ -- (CHOSEN METHOD!)**
This method includes a majority of the classes and/or components. It also automates some of the build & compiling.
- Download the latest stable release of Bootstrap from the [Downloads > Source Files page](http://getbootstrap.com/docs/4.1/getting-started/download/#source-files)
- Added the source directory to a `test` directory and then added a command to ignore the test directory in the `.gitignore` file.
- Installed the build tools for running the application using the [NPM Scripts](http://getbootstrap.com/docs/4.1/getting-started/build-tools/#using-npm-scripts) and executing the following;
    - Navigate to the root `/bootstrap` directory and run `npm install` to install our local dependencies listed in `package.json`.
    - Install Ruby, install Bundler with `gem install bundler`, and finally run `bundle install`. This will install all Ruby dependencies, such as Jekyll and plugins.
        - NOTE: You may run into an issue with See.. https://github.com/galaxypi/galaxy.ooo/issues/13#issuecomment-407851238 to solve issue.
    - Run `npm run dist` - npm run dist creates the `/dist` directory with compiled files. Uses Sass, Autoprefixer, and UglifyJS.
    - `npm test` - Same as `npm run dist` plus it runs tests locally
    - `npm run docs` - Builds and lints CSS and JavaScript for docs. You can then run the documentation locally via `npm run docs-serve`.

#### [Run the Bootstrap Docs App](http://getbootstrap.com/docs/4.1/getting-started/build-tools/#local-documentation)
- From the root `/bootstrap` directory, run `npm run docs-serve` in the command line.
- Open [`http://localhost:9001`](http://localhost:9001) in your browser.

**Comment by guylepage3** [comment]
Complete.
