### ISSUE TITLE
Create install button on home page & add footer links

### ISSUE THREAD

**Issue by guylepage3** [galaxypi/galaxy.ooo#36]
**Description**
Create install button on home page & add footer links

**Tasks**
- [ ] Change main button on home page to "Install Galaxy"
- [ ] Add GitHub link in footer
- [ ] Add Twitter link in footer

**Comment by guylepage3** [comment]
<img width="1920" alt="screenshot 2018-09-13 15 43 33" src="https://user-images.githubusercontent.com/1711854/45511851-1915a500-b76c-11e8-9ae7-37dca7fc347b.png">

**Comment by guylepage3** [comment]
<img width="1920" alt="galaxy.ooo-v0.3.7" src="https://storage.googleapis.com/galaxy.ooo/img/galaxy.ooo-v0.3.7.png">

**Comment by guylepage3** [comment]
<img width="1920" alt="galaxy ooo-v0 3 7" src="https://user-images.githubusercontent.com/1711854/45528059-94974680-b7ac-11e8-8924-4dd74401202e.png">
