### ISSUE TITLE
Create and apply transitions and animations to all components and elements

### ISSUE THREAD

**Issue by guylepage3** [galaxypi/galaxy.ooo#39]
**Description**
Create and apply transitions and animations to all components and elements.

**Tasks**
- [ ] Apply fade in animation and move down transition to Header component.
- [ ] Apply fade in animation and move up transitions to App hero elements.
- [ ] Apply fade in & delay animation and move up transitions to Footer component.
